# Generated by Django 3.0.3 on 2020-02-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_upcount_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upcount',
        ),
    ]
