# Generated by Django 3.0.3 on 2020-02-04 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('hashtags', models.TextField()),
                ('caption', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('screenshots', models.ImageField(upload_to='screenshots/')),
                ('code', models.FileField(upload_to='documents/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
