# Generated by Django 3.0.3 on 2020-02-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200205_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hashtags1',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags2',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags3',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags4',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags5',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
