# Generated by Django 3.0.3 on 2020-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200205_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtags1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags5',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Hashtags',
        ),
    ]
