# Generated by Django 3.0.3 on 2020-02-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200207_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='voteuser',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
