# Generated by Django 3.0.3 on 2020-02-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_voteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='voteuser',
        ),
    ]
